# Generated by Django 3.0.2 on 2020-01-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.Form')),
            ],
        ),
        migrations.CreateModel(
            name='McqChoiceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='McqField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('order', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.Form')),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('order', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.Form')),
            ],
        ),
        migrations.CreateModel(
            name='TextFieldResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.FormResponse')),
                ('text_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.TextField')),
            ],
        ),
        migrations.CreateModel(
            name='McqFieldResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.FormResponse')),
                ('mcq_choice_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.McqChoiceField')),
                ('mcq_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.McqField')),
            ],
        ),
        migrations.AddField(
            model_name='mcqchoicefield',
            name='mcq_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tform.McqField'),
        ),
    ]
